version: "3"

services:
  postgresdb:
    image: postgres:11.0-alpine

    volumes:
      - ./data:/stocks_products/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prod_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=shatia

  web:
    build: .
    volumes:
       - ./stocks_products:/stocks_products
    ports:
      - "8001:8000"

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgresdb
      - web
